"""empty message

Revision ID: 00baa2062efa
Revises: 0fe8cfd44db3
Create Date: 2019-11-17 04:55:11.337191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00baa2062efa'
down_revision = '0fe8cfd44db3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_code', sa.Integer(), nullable=True),
    sa.Column('city_name', sa.String(), nullable=True),
    sa.Column('state_code', sa.Integer(), nullable=True),
    sa.Column('state_name', sa.String(), nullable=True),
    sa.Column('active', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('city', sa.Column('city_code', sa.Integer(), nullable=True))
    op.drop_column('city', 'active')
    op.drop_column('city', 'state_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('city', sa.Column('state_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('city', sa.Column('active', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('city', 'city_code')
    op.drop_table('state')
    # ### end Alembic commands ###
