"""empty message

Revision ID: 04624b2fb12d
Revises: 6af9e51f8b01
Create Date: 2020-01-08 00:04:00.824612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04624b2fb12d'
down_revision = '6af9e51f8b01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('state')
    op.drop_table('city')
    op.add_column('file', sa.Column('server_file_name', sa.String(), nullable=True))
    op.add_column('patient', sa.Column('notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient', 'notes')
    op.drop_column('file', 'server_file_name')
    op.create_table('city',
    sa.Column('city_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('city_code', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_table('state',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('city_code', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('city_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('state_code', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('state_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('active', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='state_pkey')
    )
    # ### end Alembic commands ###
