"""empty message

Revision ID: 0fe8cfd44db3
Revises: 6a1a7335c223
Create Date: 2019-11-02 20:44:03.902390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fe8cfd44db3'
down_revision = '6a1a7335c223'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('city_name', sa.String(), nullable=True),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.Column('state_name', sa.String(), nullable=True),
    sa.Column('active', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('file',
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('file_url', sa.String(), nullable=True),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('date_uploaded', sa.DateTime(), nullable=True),
    sa.Column('user_uploaded', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('file_id')
    )
    op.add_column('examination', sa.Column('patient_id', sa.Integer(), nullable=True))
    op.drop_column('examination', 'file_name')
    op.drop_column('examination', 'file_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('examination', sa.Column('file_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('examination', sa.Column('file_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('examination', 'patient_id')
    op.drop_table('file')
    op.drop_table('city')
    # ### end Alembic commands ###
