"""empty message

Revision ID: 6a1a7335c223
Revises: 6c19bcc4f3ac
Create Date: 2019-10-28 19:43:48.811139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a1a7335c223'
down_revision = '6c19bcc4f3ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('examination', sa.Column('file_name', sa.String(), nullable=True))
    op.add_column('examination', sa.Column('file_url', sa.String(), nullable=True))
    op.drop_column('examination', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('examination', sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('examination', 'file_url')
    op.drop_column('examination', 'file_name')
    # ### end Alembic commands ###
