"""empty message

Revision ID: 6af9e51f8b01
Revises: 6a88e67ca343
Create Date: 2020-01-06 23:39:10.146849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6af9e51f8b01'
down_revision = '6a88e67ca343'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('city')
    op.drop_table('state')
    op.add_column('file', sa.Column('server_file_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'server_file_name')
    op.create_table('state',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('city_code', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('city_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('state_code', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('state_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('active', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='state_pkey')
    )
    op.create_table('city',
    sa.Column('city_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('city_code', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
