"""empty message

Revision ID: 830a1be44e40
Revises: 04624b2fb12d
Create Date: 2020-01-12 16:41:33.125606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '830a1be44e40'
down_revision = '04624b2fb12d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment', sa.Column('date_updated', sa.DateTime(), nullable=True))
    op.add_column('appointment', sa.Column('user_updated', sa.String(length=50), nullable=True))
    op.add_column('patient', sa.Column('updated_date', sa.DateTime(), nullable=True))
    op.add_column('patient', sa.Column('updated_user', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('updated_date', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('updated_user', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'updated_user')
    op.drop_column('user', 'updated_date')
    op.drop_column('patient', 'updated_user')
    op.drop_column('patient', 'updated_date')
    op.drop_column('appointment', 'user_updated')
    op.drop_column('appointment', 'date_updated')
    # ### end Alembic commands ###
